### ISSUE TITLE
Detected blocking call to import_module inside the event loop

### ISSUE THREAD

**Issue by tjorim** [frenck/spook#740] opened 2024-04-24 20:53 UTC
### What version of Spook are you using?

v2.2.4

### What version of Home Assistant are you using?

2024.5.0b0

### The problem

```
Logger: homeassistant.util.loop
Source: util/loop.py:99
First occurred: 22:13:11 (140 occurrences)
Last logged: 22:15:28

Detected blocking call to import_module inside the event loop by custom integration 'spook' at custom_components/spook/templating.py, line 122: module = importlib.import_module(f".{module_path}", __package__) (offender: /config/custom_components/spook/templating.py, line 122: module = importlib.import_module(f".{module_path}", __package__)), please create a bug report at https://github.com/frenck/spook/issues
Detected blocking call to import_module inside the event loop by custom integration 'spook' at custom_components/spook/services.py, line 272: module = importlib.import_module(f".{module_path}", __package__) (offender: /config/custom_components/spook/services.py, line 272: module = importlib.import_module(f".{module_path}", __package__)), please create a bug report at https://github.com/frenck/spook/issues
Detected blocking call to import_module inside the event loop by custom integration 'spook' at custom_components/spook/util.py, line 76: module = importlib.import_module(f".{module_path}", __package__) (offender: /config/custom_components/spook/util.py, line 76: module = importlib.import_module(f".{module_path}", __package__)), please create a bug report at https://github.com/frenck/spook/issues
Detected blocking call to import_module inside the event loop by custom integration 'spook' at custom_components/spook/repairs.py, line 276: module = importlib.import_module(f".{module_path}", __package__) (offender: /config/custom_components/spook/repairs.py, line 276: module = importlib.import_module(f".{module_path}", __package__)), please create a bug report at https://github.com/frenck/spook/issues
```

**Comment by frenck** [comment] 2024-04-24 21:13
Duplicate of #681, fixed by #722

**Closed by frenck** 2024-04-24 21:13 UTC
