### ISSUE TITLE
Ignore Button Missing

### ISSUE THREAD

**Issue by holdestmade** [frenck/spook#199] opened 2023-06-02 09:27 UTC
I have a few entities that are unavailable until they are used (in the custom emby component)

Spook finds these entities, but I cannot ignore them. If I click submit, the repair goes away but reappears shortly afterwards:

![1](https://github.com/frenck/spook/assets/13977244/78fe509e-91c3-4f6a-9d47-209fd8383836)

**Comment by frenck** [comment] 2023-06-02 09:35
Yeah, this is a bit of the "meh" part of the HA repairs.

This one is marked as "Submit will mark it fixed" (until the next detection/inspection run for Spook). However, the ones you can mark fixed in HA, you can't ignore? Which is a bit odd actually.

The reason why I allowed marking it as fixed, is because I haven't tried hooking into the updates of dashboards yet (which I would need to know when something changed and this determines if the issue is solved).

As I'm already hacking on this, I'll take a look if I can hook into listening for Lovelace changes.

**Comment by frenck** [comment] 2023-06-02 09:36
> I have a few entities that are unavailable until they are used (in the custom emby component)

PS: This is caused by the lack of unique IDs on those entities. Should generally be an easy fix for upstream...

**Comment by holdestmade** [comment] 2023-06-02 09:37
OK thanks, I'll mention it to the emby custom component dev.

**Comment by frenck** [comment] 2023-06-02 09:59
Found a way to automatically detect dashboard changes and let Spook clean up / update the raised repair issues by itself in #202 🤘 

This behavioral change causes HA to enable the ignore button.

../Frenck

**Closed** 2023-06-02 09:59 UTC

**Comment by holdestmade** [comment] 2023-06-02 11:39
That did it, many thanks
