### ISSUE TITLE
Unexpected exception from <function AbstractSpookRepair.async_activate.<locals>._async_inspect

### ISSUE THREAD

**Issue by avbor** [frenck/spook#609] opened 2024-02-11 13:06 UTC
### What version of Spook are you using?

2.2.0

### What version of Home Assistant are you using?

2024.2.1

### The problem

Logger: custom_components.spook
Source: helpers/debounce.py:114
Integration: Spook ([documentation](https://spook.boo/), [issues](https://github.com/frenck/spook/issues))
First occurred: 15:56:14 (1 occurrences)
Last logged: 15:56:14

Unexpected exception from <function AbstractSpookRepair.async_activate.<locals>._async_inspect at 0x7f8c8672ef20>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 114, in _handle_timer_finish
    await task
  File "/config/custom_components/spook/repairs.py", line 134, in _async_inspect
    await self.async_inspect()
  File "/config/custom_components/spook/ectoplasms/automation/repairs/unknown_service_references.py", line 67, in async_inspect
    _async_find_services_in_sequence(
  File "/config/custom_components/spook/ectoplasms/automation/repairs/unknown_service_references.py", line 136, in _async_find_services_in_sequence
    _async_find_services_in_sequence(called_services, step[CONF_SEQUENCE])
                                                      ~~~~^^^^^^^^^^^^^^^
KeyError: 'sequence'

### Anything in the logs? Paste it here!

_No response_

**Comment by frenck** [comment] 2024-02-11 13:34
duplicate of #608 fixed in #607

**Closed by frenck** 2024-02-11 13:34 UTC
