### ISSUE TITLE
Feature Req: add switches to addons 

### ISSUE THREAD

**Issue by jokerigno** [frenck/spook#140] opened 2023-04-26 15:29 UTC
Do you think is possible to create spook switches to see status of addon without entering the setting page?

Thanks!

**Comment by frenck** [comment] 2023-04-26 16:20
Add-ons already have an entity to see if they are running?

**Comment by frenck** [comment] 2023-04-26 16:21
But, in either case, this is not a bug, so it should not be reported as an issue.

Closing.

../Frenck

**Closed by frenck** 2023-04-26 16:21 UTC
